DROP TABLE IF EXISTS `#__bagallery_galleries`;
DROP TABLE IF EXISTS `#__bagallery_category`;
DROP TABLE IF EXISTS `#__bagallery_items`;
DROP TABLE IF EXISTS `#__bagallery_users`;
DROP TABLE IF EXISTS `#__bagallery_api`;
DROP TABLE IF EXISTS `#__bagallery_tags`;
DROP TABLE IF EXISTS `#__bagallery_tags_map`;
DROP TABLE IF EXISTS `#__bagallery_colors`;
DROP TABLE IF EXISTS `#__bagallery_colors_map`;