ALTER TABLE `#__bagallery_galleries` ADD `disable_lightbox` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__bagallery_galleries` ADD `disable_caption` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__bagallery_galleries` CHANGE `title_font_color` `title_font_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `header_icons_color` `header_icons_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `close_icon_color` `close_icon_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `nav_button_bg` `nav_button_bg` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `nav_button_icon` `nav_button_icon` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `lightbox_border` `lightbox_border` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `title_color` `title_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `category_color` `category_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `description_color` `description_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `bg_color` `bg_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `bg_color_hover` `bg_color_hover` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `border_color` `border_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `font_color` `font_color` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `font_color_hover` `font_color_hover` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `bg_active` `bg_active` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `bg_hover_active` `bg_hover_active` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `border_color_active` `border_color_active` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `font_color_active` `font_color_active` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `font_color_hover_active` `font_color_hover_active` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `pagination_bg` `pagination_bg` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `pagination_bg_hover` `pagination_bg_hover` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `pagination_border` `pagination_border` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `pagination_font` `pagination_font` VARCHAR(40);
ALTER TABLE `#__bagallery_galleries` CHANGE `pagination_font_hover` `pagination_font_hover` VARCHAR(40);